# @package _global_

# Be careful when using _raw, history
obs:
  obs_dict:
    actor_obs: [
      base_ang_vel,
      projected_gravity,
      command_lin_vel,
      command_ang_vel,
      dof_pos,
      dof_vel,
      actions,
      history_actor
    ]

    critic_obs: [
      base_lin_vel,
      base_ang_vel,
      projected_gravity,
      command_lin_vel,
      command_ang_vel,
      dof_pos,
      dof_vel,
      actions,
      history_critic
    ]

  obs_auxiliary: # define those coumpounds in obs_dict, for example, you can define different long/short history with different length

    history_actor: {
      base_ang_vel: 8,
      projected_gravity: 8,
      command_lin_vel: 8,
      command_ang_vel: 8,
      dof_pos: 8,
      dof_vel: 8,
      actions: 8,
    }

    history_critic: {
      base_lin_vel: 8,
      base_ang_vel: 8,
      projected_gravity: 8,
      command_lin_vel: 8,
      command_ang_vel: 8,
      dof_pos: 8,
      dof_vel: 8,
      actions: 8,
    }

  obs_scales: {
    base_lin_vel: 2.0,
    base_ang_vel: 0.25,
    projected_gravity: 1.0,
    command_lin_vel: 1.0,
    command_ang_vel: 1.0,
    dof_pos: 1.0,
    dof_vel: 0.05,
    #history: 1.0,
    actions: 1.0,
    history_actor: 1.0,
    history_critic: 1.0,
  }

  noise_scales: {
    base_lin_vel: 0.0,
    base_ang_vel: 0.0,
    projected_gravity: 0.0,
    command_lin_vel: 0.0,
    command_ang_vel: 0.0,
    dof_pos: 0.0,
    dof_vel: 0.0,
    actions: 0.0,
    #history: 0.0,
    history_actor: 0.0,
    history_critic: 0.0,
  }

  # obs_dims should use list instead of dict
  # will be converted to dict in `pre_process_config`
  obs_dims:
    - base_lin_vel: 3
    - base_ang_vel: 3
    - projected_gravity: 3
    - command_lin_vel: 2
    - command_ang_vel: 1
    - dof_pos: ${robot.dof_obs_size}
    - dof_vel: ${robot.dof_obs_size}
    - actions: ${robot.dof_obs_size}
